DiscretizeKBins:
  configurations:
    - name: uniform
      config:
        strategy: uniform
        n_bins: 5
    - name: quantile
      config:
        strategy: quantile
        n_bins: 5

HandleUnivariateOutliers:
  configurations:
    - name: z-score
      config:
        method: z-score
    - name: IQR
      config:
        method: IQR

DropZeroVariance:
  configurations:
    - name: int
      config:
        inputs: integer
    - name: float
      config:
        inputs: floating
    - name: str
      config:
        inputs: string

FillNA:
  configurations:
    - name: float
      config:
        inputs: floating
        fill_value: 0
    - name: int
      config:
        inputs: integer
        fill_value: 0
    - name: str
      config:
        inputs: string
        fill_value: "NULL"

ImputeMode:
  configurations:
    - name: int
      config:
        inputs: integer
    - name: float
      config:
        inputs: floating
    - name: str
      config:
        inputs: string

ExpandDate:
  configurations:
    - name: d
      config:
        inputs: date
        components:
          - day
    - name: w
      config:
        inputs: date
        components:
          - week
    - name: m
      config:
        inputs: date
        components:
          - month
    - name: y
      config:
        inputs: date
        components:
          - year
    - name: dow
      config:
        inputs: date
        components:
          - dow
    - name: doy
      config:
        inputs: date
        components:
          - doy

ExpandTime:
  configurations:
    - name: h
      config:
        inputs: time
        components:
          - hour
    - name: m
      config:
        inputs: time
        components:
          - minute
    - name: s
      config:
        inputs: time
        components:
          - second
    - name: ms
      config:
        inputs: time
        components:
          - millisecond

ExpandTimestamp:
  configurations:
    - name: ms
      config:
        inputs: timestamp
        components:
          - millisecond
    - name: s
      config:
        inputs: timestamp
        components:
          - second
    - name: m
      config:
        inputs: timestamp
        components:
          - minute
    - name: d
      config:
        inputs: timestamp
        components:
          - day
    - name: week
      config:
        inputs: timestamp
        components:
          - week
    - name: mon
      config:
        inputs: timestamp
        components:
          - month
    - name: y
      config:
        inputs: timestamp
        components:
          - year
    - name: dow
      config:
        inputs: timestamp
        components:
          - dow
    - name: doy
      config:
        inputs: timestamp
        components:
          - doy
