project:
  type: website
  preview:
    port: 8000

highlight-style: ayu
code-annotations: hover

metadata-files:
  - _sidebar.yml

website:
  title: "IbisML"
  description: "IbisML is a library for building scalable ML pipelines using Ibis."
  favicon: logo.svg

  # search
  search:
    location: navbar
    type: overlay

  # options
  reader-mode: false
  twitter-card: true
  back-to-top-navigation: true
  repo-url: https://github.com/ibis-project/ibis-ml
  repo-actions: [edit, issue]
  repo-branch: main
  repo-subdir: docs
  issue-url: https://github.com/ibis-project/ibis-ml/issues

  # footer
  page-footer:
    border: false
    left: ""
    right:
      - icon: github
        href: https://github.com/ibis-project/ibis-ml
      - icon: zulip
        href: https://ibis-project.zulipchat.com/#narrow/stream/426262-ibis-ml

  # nav
  navbar:
    logo: logo.svg
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/ibis-project/ibis-ml
          - text: Open an issue
            url: https://github.com/ibis-project/ibis-ml/issues

    left:
      - sidebar:reference

  sidebar:
    - id: ""
    - id: reference
      title: "Reference"
      style: "docked"
      collapse-level: 2
      contents:
        - section: Core API
          contents:
            - reference/core.qmd
            - reference/selectors.qmd

        - section: Steps
          contents:
            - reference/steps-imputation.qmd
            - reference/steps-encoding.qmd
            - reference/steps-standardization.qmd
            - reference/steps-discretization.qmd
            - reference/steps-feature-selection.qmd
            - reference/steps-feature-engineering.qmd
            - reference/steps-temporal.qmd
            - reference/steps-other.qmd

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    toc: true
    css: styles.css

quartodoc:
  package: ibisml
  title: Reference
  sidebar: reference/_sidebar.yml
  dynamic: true
  render_interlinks: false
  options:
    member_options:
      signature_name: short
  sections:
    - title: Core
      package: ibisml
      contents:
        - kind: page
          path: core
          summary:
            name: Common
            desc: Core APIs
          contents:
            - Recipe

        - kind: page
          path: selectors
          summary:
            name: Selectors
            desc: Select sets of columns by name, type, or other properties
          contents:
            - cols
            - contains
            - endswith
            - startswith
            - matches
            - numeric
            - nominal
            - categorical
            - string
            - integer
            - floating
            - temporal
            - date
            - time
            - timestamp
            - has_type
            - where
            - everything
            - selector

    - title: Steps
      desc: Define steps in a recipe
      package: ibisml
      contents:
        - kind: page
          path: steps-imputation
          summary:
            name: Imputation
            desc: Imputation and handling of missing values
          contents:
            - ImputeMean
            - ImputeMode
            - ImputeMedian
            - FillNA

        - kind: page
          path: steps-encoding
          summary:
            name: Encoding
            desc: Encoding of categorical and string columns
          contents:
            - OneHotEncode
            - CategoricalEncode
            - CountEncode
            - TargetEncode

        - kind: page
          path: steps-standardization
          summary:
            name: Standardization
            desc: Standardization and normalization of numeric columns
          contents:
            - ScaleStandard

        - kind: page
          path: steps-discretization
          summary:
            name: Discretization
            desc: Discretization of numeric columns
          contents:
            - DiscretizeKBins

        - kind: page
          path: steps-feature-selection
          summary:
            name: Feature selection
            desc: Selecting useful features for modeling
          contents:
            - ZeroVariance

        - kind: page
          path: steps-feature-engineering
          summary:
            name: Feature engineering
            desc: Generating new features
          contents:
            - PolynomialFeatures

        - kind: page
          path: steps-temporal
          summary:
            name: Temporal
            desc: Feature extraction for temporal columns
          contents:
            - ExpandDateTime
            - ExpandDate
            - ExpandTime

        - kind: page
          path: steps-other
          summary:
            name: Other
            desc: Other common tabular operations
          contents:
            - Cast
            - Drop
            - MutateAt
            - Mutate
