DiscretizeKBins:
  configurations:
    - name: uniform
      config:
        strategy: uniform
        n_bins: 5
    - name: quantile
      config:
        strategy: quantile
        n_bins: 5

DropZeroVariance:
  configurations:
    - name: numeric
      config:
        inputs: numeric
    - name: string
      config:
        inputs: string

FillNA:
  configurations:
    - name: float
      config:
        inputs: floating
        fill_value: 0
    - name: integer
      config:
        inputs: integer
        fill_value: 0
    - name: string
      config:
        inputs: string
        fill_value: "NULL"

ImputeMode:
  configurations:
    - name: numeric
      config:
        inputs: numeric
    - name: string
      config:
        inputs: string

ExpandDate:
  configurations:
    - name: day, month, year
      config:
        inputs: date
        components:
          - day
          - week
          - month
          - year
    - name: month
      config:
        inputs: date
        components:
          - month
    - name: day of week
      config:
        inputs: date
        components:
          - dow
    - name: day of year
      config:
        inputs: date
        components:
          - doy

ExpandDateTime:
  configurations:
    - name: year, month, day
      config:
        inputs: timestamp
        components:
          - month
          - year
          - hour
          - minute
          - second
    - name: minute, second
      config:
        inputs: timestamp
        components:
          - minute
          - second
    - name: day of week
      config:
        inputs: timestamp
        components:
          - dow
    - name: day of year
      config:
        inputs: timestamp
        components:
          - doy

ExpandTime:
  configurations:
    - name: hour
      config:
        inputs: time
        components:
          - hour
    - name: minute
      config:
        inputs: time
        components:
          - minute
    - name: second
      config:
        inputs: time
        components:
          - hour
          - minute
          - second
          - millisecond
    - name: millisecond
      config:
        inputs: time
        components:
          - millisecond
