name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  release:
    types: [published]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ibisml
        run: |
          pip install ".[dev]"

      - name: Run tests
        run: |
          pytest tests/

  publish:
    needs: [lint, test]
    name: Publish Release to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: pip install build

      - name: Build sdist and wheel
        run: python -m build
